project:
  type: book
  output-dir: docs

book:
  title: "Techninis aprašas SADM transliacijoms"
  author: "Justas Mundeikis"
  date: now
  lang: lt
  search: true
  twitter-card: true
  site-url: https://example.com
  sidebar:
    style: "docked"
    search: true
  chapters:
    - index.qmd
    - 0_process_overview.qmd
    - 1_hardware_software.qmd
    - 2_preparation.qmd
    - 3_live.qmd
    - 4_post_edit.qmd
format:
  html:
    theme: spacelab
    fig-align: center
    title-block-banner: true