# Įvadas {.unnumbered}
 
Šis techninis aprašas skirtas SADM darbuotojams, kurie turės (jeigu) užtikrinti SADM organizuojamų dvišalių bei trišalių susitikimų, vykstančių per `TEAMS` platformą, tiesioginę transliaciją internetu per [Youtube](https://www.youtube.com/channel/UCSIDVgAzDrQ9P43ccXTznVA) SADM paskyrą.
 
Susitikimų, posėdžių bei diskusijų transliavimas užtikrina vykdomo socialinio dialogo skaidrumą bei tiek SADM, tiek kitų socialinių partnerių atskaitomybę visuomenei bei reprezentuojamoms interesų grupėms.

Kartu transliavimas užtikrina archyvavimo funkciją: transliuoti video išsaugomi platformoje Youtube. Šiuose video įrašuose būna nurodytos laiko žymos, o tai panaikina poreikį transkribuoti posėdžius. Visgi saugumo sumetimais rekomenduojama ir toliau susitikimų organizatoriams tęsti `TEAMS` posėdžių įrašo darymą, kuris galėtų būti panaudotas tuo atveju, jeigu dėl techninių priežasčių įvyktų kokia nors transliacijos klaida.

::: {.callout-warning}
Prisimenant premjero S.Skvernelio susitikimo su medikais istoriją bei dingusius susitikimo garso įrašus, rekomenduojama transliuoti visus vadovybės susitikimus su interesų grupėmis
:::

Šis aprašas nedetalizuoja, kuri SADM komanda turi užtikrinti transliavimo vykdymą: 
 
* darbo teisės komanda
* komunikacijos komanda
* IT komanda
 
Kiekviena komanda turi savo galimų pliusų ir minusų:
 
* darbo teisės komanda
    * minusas: tikėtinas mažesnis IT raštingumas, galimi konfliktai su kitų renginių transliavimu nesuderinus su komunikacijos komanda
    * pliusas: visas procesas vienose rankose
 
* komunikacijos komanda
    * minusas: tikėtinas mažesnis IT raštingumas, papildomas derinimas su organizuojančia komanda
    * pliusas: centralizuotos komunikacijos kompetencijos organizacijoje
 
* IT komanda
    * minusas: reikalingas papildomas derinimas su organizuojančia komanda ir su komunikacijos komanda dėl galimai persidengiančių (laike) transliacijų
    * pliusas: tikėtinas didesnis IT raštingumas ir kompetencijas spręsti ad-hoc kylančias IT problemas
 
Šis aprašas skirtas `TEAMS` platformoje vykstančių susitikimų retransliavimui, tačiau yra lengvai adaptuojamas ZOOM / JITSI ir kitų IT platformų naudojimui, kurios galėtų būti naudojamos ateityje vietoj `TEAMS` platformos.
 
Taip pat daroma prielaida, jog archyvavimo ir organizavimo tikslais taip pat naudojama `TEAMS` programa. Jeigu ateityje tai pasikeistų, atitinkamai reiktų adaptuoti šiame apraše esančius principus naujai platformai. 
 
## Pagalba
 
Nepaisant išsamaus techninio aprašo, transliacijas turintiems vykdyti darbuotojams gali kilti papildomų klausimų, poreikis padėti spręsti iškilusias problemas.
 
Pagalbos algoritmas turėtų būti toks:
 
1. Jeigu kyla papildomų klausimų, techninis raportas nėra aiškus, reiktų jog būtų papildytas / pataisytas aprašas:
    * kontaktuoti Justą Mundeikį
2. Jeigu kyla techninių problemų (nepavyksta instaliuoti programų / klaidos)
    * kontaktuoti SADM IT komandą
    * jeigu jie negali padėti kontaktuoti Justą Mundeikį
3. Jeigu kyla poreikis papildomai pasiaiškinti transliavimo mechanizmą, galimi 1:1 individualūs susitikimai su Justu Mundeikiu, kuriuos reiktų derinti individualiai

::: {.callout-note}
Šis dokumentas yra “gyvas” - reaguojant į pastabas, besikeičiantų IT sistemų veikimą, šis dokumentus bus atnaujinimas ir stengsis reflektuoti esamą situaciją, todėl nerekomenduojama šio dokumento spausdinti, o patartina naudotis internetine versija
:::